[package]
name = "cbqn"
description = "Embed BQN in Rust via CBQN FFI"
version = "0.0.8"
edition = "2021"
license = "GPL-3.0-only"
keywords = ["CBQN", "BQN", "APL", "array"]
readme = "README.md"
homepage = "https://github.com/Detegr/cbqn-rs"
repository = "https://github.com/Detegr/cbqn-rs.git"
documentation = "https://detegr.github.io/cbqn-rs/cbqn"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbqn-sys = "0.0.8"
once_cell = "1.12.0"
parking_lot = "0.12.1"
