[package]
name = "cbqn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbqn-sys = { git = "https://github.com/Detegr/cbqn-sys.git" }
once_cell = "1.12.0"
parking_lot = "0.12.1"
