[package]
name = "cbqn"
version = "0.0.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbqn-sys = "0.0.8"
once_cell = "1.12.0"
parking_lot = "0.12.1"
